baseURL = 'https://www.frenchfamily.fr/'
title = 'French Family'
languageCode = 'en-us'
buildFuture = true
disableHugoGeneratorInject = true
enableRobotsTXT = false

[markup.highlight]
  style = "catppuccin-mocha"
  # uses inline styles (easy, no CSS setup)
  noClasses = true

[taxonomies]
  category = 'categories'
  tag = 'tags'

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = 'about'
    weight = 10
  [[menus.main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 20
 # [[menus.footer]]
 #   name = 'Support'
 #   pageRef = '/support'
 #   weight = 10
