baseURL = 'https://www.frenchfamily.fr/'
#baseURL = 'https://example.org/'
title = 'French Family'
languageCode = 'en-us'
buildFuture = true

[markup.highlight]
  # style = "rose-pine"
  # style = "tokyonight-moon"
  # style = "tokyonight-storm"
  # style = "tokyonight-night"
  style = "catppuccin-mocha"
  # style = "catppuccin-frappe"
  # style = "catppuccin-macchiato"
  # style = "rose-pine-moon"
  # uses inline styles (easy, no CSS setup)
  noClasses = true

[taxonomies]
  category = 'categories'
  tag = 'tags'

