baseURL = 'https://www.frenchfamily.fr/'
title = 'French Family'
languageCode = 'fr-fr'
buildFuture = true
disableHugoGeneratorInject = true
enableRobotsTXT = false

[markup.highlight]
  style = "catppuccin-mocha"
  # uses inline styles (easy, no CSS setup)
  noClasses = true

[taxonomies]
  category = 'categories'
  tag = 'tags'

[menus]
  #[[menus.main]]
  #  name = 'Home'
  #  pageRef = '/'
  #  weight = 10
  [[menus.main]]
    name = 'About'
    pageRef = '/about/'
    weight = 10
  [[menus.main]]
    name = 'Univers One Piece'
    pageRef = '/posts/Univers_One_Piece/'
    weight = 20
  [[menus.main]]
    name = 'Univers Zelda'
    pageRef = '/posts/Univers_Zelda/'
    weight = 30
